/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppAttributesIndexRouteImport } from './routes/_app.attributes.index'
import { Route as AppBranchesIndexRouteImport } from './routes/_app.branches.index'
import { Route as AppBrandsIndexRouteImport } from './routes/_app.brands.index'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app.categories.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app.customers.$customerId'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as AppDeliveryChargesIndexRouteImport } from './routes/_app.delivery-charges.index'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app.employees.index'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/_app.employees.$employeeId'
import { Route as AppExpensesIndexRouteImport } from './routes/_app.expenses.index'
import { Route as AppExpensesExpenseIdRouteImport } from './routes/_app.expenses.$expenseId'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app.invoices.$invoiceId'
import { Route as AppMovementsIndexRouteImport } from './routes/_app.movements.index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app.orders.$orderId'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppProductsProductIdRouteImport } from './routes/_app.products.$productId'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppSalesIndexRouteImport } from './routes/_app.sales.index'
import { Route as AppStockIndexRouteImport } from './routes/_app.stock.index'
import { Route as AppTransfersIndexRouteImport } from './routes/_app.transfers.index'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as ApiPublicBackendSplatRouteImport } from './routes/api/public/backend/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAttributesIndexRoute = AppAttributesIndexRouteImport.update({
  id: '/attributes/',
  path: '/attributes/',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesIndexRoute = AppBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsIndexRoute = AppBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryChargesIndexRoute = AppDeliveryChargesIndexRouteImport.update({
  id: '/delivery-charges/',
  path: '/delivery-charges/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesExpenseIdRoute = AppExpensesExpenseIdRouteImport.update({
  id: '/expenses/$expenseId',
  path: '/expenses/$expenseId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsIndexRoute = AppMovementsIndexRouteImport.update({
  id: '/movements/',
  path: '/movements/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppStockIndexRoute = AppStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersIndexRoute = AppTransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicBackendSplatRoute = ApiPublicBackendSplatRouteImport.update({
  id: '/api/public/backend/$',
  path: '/api/public/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/pos': typeof AppPosRoute
  '/profile': typeof AppProfileRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/attributes/': typeof AppAttributesIndexRoute
  '/branches/': typeof AppBranchesIndexRoute
  '/brands/': typeof AppBrandsIndexRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/delivery-charges/': typeof AppDeliveryChargesIndexRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/movements/': typeof AppMovementsIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/stock/': typeof AppStockIndexRoute
  '/transfers/': typeof AppTransfersIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/api/public/backend/$': typeof ApiPublicBackendSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/pos': typeof AppPosRoute
  '/profile': typeof AppProfileRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/attributes': typeof AppAttributesIndexRoute
  '/branches': typeof AppBranchesIndexRoute
  '/brands': typeof AppBrandsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/delivery-charges': typeof AppDeliveryChargesIndexRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/movements': typeof AppMovementsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/stock': typeof AppStockIndexRoute
  '/transfers': typeof AppTransfersIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/api/public/backend/$': typeof ApiPublicBackendSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/_app/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/attributes/': typeof AppAttributesIndexRoute
  '/_app/branches/': typeof AppBranchesIndexRoute
  '/_app/brands/': typeof AppBrandsIndexRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/delivery-charges/': typeof AppDeliveryChargesIndexRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/movements/': typeof AppMovementsIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/stock/': typeof AppStockIndexRoute
  '/_app/transfers/': typeof AppTransfersIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/api/public/backend/$': typeof ApiPublicBackendSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/no-access'
    | '/pos'
    | '/profile'
    | '/customers/$customerId'
    | '/employees/$employeeId'
    | '/expenses/$expenseId'
    | '/invoices/$invoiceId'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/attributes/'
    | '/branches/'
    | '/brands/'
    | '/categories/'
    | '/customers/'
    | '/dashboard/'
    | '/delivery-charges/'
    | '/employees/'
    | '/expenses/'
    | '/invoices/'
    | '/movements/'
    | '/orders/'
    | '/products/'
    | '/reports/'
    | '/sales/'
    | '/stock/'
    | '/transfers/'
    | '/users/'
    | '/api/public/backend/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/no-access'
    | '/pos'
    | '/profile'
    | '/customers/$customerId'
    | '/employees/$employeeId'
    | '/expenses/$expenseId'
    | '/invoices/$invoiceId'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/attributes'
    | '/branches'
    | '/brands'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/delivery-charges'
    | '/employees'
    | '/expenses'
    | '/invoices'
    | '/movements'
    | '/orders'
    | '/products'
    | '/reports'
    | '/sales'
    | '/stock'
    | '/transfers'
    | '/users'
    | '/api/public/backend/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/login'
    | '/no-access'
    | '/_app/pos'
    | '/_app/profile'
    | '/_app/customers/$customerId'
    | '/_app/employees/$employeeId'
    | '/_app/expenses/$expenseId'
    | '/_app/invoices/$invoiceId'
    | '/_app/orders/$orderId'
    | '/_app/products/$productId'
    | '/_app/attributes/'
    | '/_app/branches/'
    | '/_app/brands/'
    | '/_app/categories/'
    | '/_app/customers/'
    | '/_app/dashboard/'
    | '/_app/delivery-charges/'
    | '/_app/employees/'
    | '/_app/expenses/'
    | '/_app/invoices/'
    | '/_app/movements/'
    | '/_app/orders/'
    | '/_app/products/'
    | '/_app/reports/'
    | '/_app/sales/'
    | '/_app/stock/'
    | '/_app/transfers/'
    | '/_app/users/'
    | '/api/public/backend/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  ApiPublicBackendSplatRoute: typeof ApiPublicBackendSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attributes/': {
      id: '/_app/attributes/'
      path: '/attributes'
      fullPath: '/attributes/'
      preLoaderRoute: typeof AppAttributesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/': {
      id: '/_app/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AppBranchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/': {
      id: '/_app/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AppBrandsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delivery-charges/': {
      id: '/_app/delivery-charges/'
      path: '/delivery-charges'
      fullPath: '/delivery-charges/'
      preLoaderRoute: typeof AppDeliveryChargesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$employeeId': {
      id: '/_app/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/$expenseId': {
      id: '/_app/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AppExpensesExpenseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements/': {
      id: '/_app/movements/'
      path: '/movements'
      fullPath: '/movements/'
      preLoaderRoute: typeof AppMovementsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/': {
      id: '/_app/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AppStockIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/': {
      id: '/_app/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AppTransfersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/backend/$': {
      id: '/api/public/backend/$'
      path: '/api/public/backend/$'
      fullPath: '/api/public/backend/$'
      preLoaderRoute: typeof ApiPublicBackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppPosRoute: typeof AppPosRoute
  AppProfileRoute: typeof AppProfileRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRoute
  AppExpensesExpenseIdRoute: typeof AppExpensesExpenseIdRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppAttributesIndexRoute: typeof AppAttributesIndexRoute
  AppBranchesIndexRoute: typeof AppBranchesIndexRoute
  AppBrandsIndexRoute: typeof AppBrandsIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDeliveryChargesIndexRoute: typeof AppDeliveryChargesIndexRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppMovementsIndexRoute: typeof AppMovementsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppStockIndexRoute: typeof AppStockIndexRoute
  AppTransfersIndexRoute: typeof AppTransfersIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPosRoute: AppPosRoute,
  AppProfileRoute: AppProfileRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRoute,
  AppExpensesExpenseIdRoute: AppExpensesExpenseIdRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppAttributesIndexRoute: AppAttributesIndexRoute,
  AppBranchesIndexRoute: AppBranchesIndexRoute,
  AppBrandsIndexRoute: AppBrandsIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDeliveryChargesIndexRoute: AppDeliveryChargesIndexRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppMovementsIndexRoute: AppMovementsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppStockIndexRoute: AppStockIndexRoute,
  AppTransfersIndexRoute: AppTransfersIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  ApiPublicBackendSplatRoute: ApiPublicBackendSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
